version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
    - "3306:3306"
    expose:
      - "3306"
    networks:
      - user-app-network

  user-portal-service:
    restart: always
    container_name: user-portal-service
    build:
      context: .
      dockerfile: ./user-portal/Dockerfile
    expose:
      - "8080"
    depends_on:
       - db
    networks:
      - user-app-network
#command: sh -c './wait-for db:3306'
    health:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=testdb 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }

  nginx-angular:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    expose:
      - "80"
    ports:
      - "8080:8080"
    depends_on:
      - user-portal-service
    networks:
      - user-app-network

networks:
  user-app-network:
    driver: bridge
:wq


