version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
    - "3306:3306"
    expose:
      - "3306"
    networks:
      - user-app-network
    #command:  bash -c "/wait-for-it.sh -t 0 mysql:3306"

  user-portal-service:
    restart: always
    container_name: user-portal-service
    build:
      context: .
      dockerfile: ./user-portal/Dockerfile
    expose:
      - "8080"
    depends_on:
       - db
    #command: ["./wait-for-it.sh", "db:5432" ]
    networks:
      - user-app-network
    #command: ["/wait-for-it.sh", "db:3306", "--", "java", "-jar","target/user-portal.jar"]
    command: sh -c "/wait && java -jar /target/user-portal.jar"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  nginx-angular:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    expose:
      - "80"
    ports:
      - "8080:8080"
    networks:
      - user-app-network

networks:
  user-app-network:
    driver: bridge
