version: '3'
services:
  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: testdb
  #   ports:
  #   - "3306:3306"
  #   expose:
  #     - "3306"
  #   networks:
  #     - user-app-network
  #   #command:  bash -c "/wait-for-it.sh -t 0 mysql:3306"

  # user-portal-service:
  #   restart: always
  #   container_name: user-portal-service
  #   build:
  #     context: .
  #     dockerfile: ./user-portal/Dockerfile
  #   expose:
  #     - "8080"
  #   depends_on:
  #      - db
  #   #command: ["./wait-for-it.sh", "db:5432" ]
  #   networks:
  #     - user-app-network
  #   command: ["/wait-for-it.sh", "db:8002", "--", "java", "-jar","target/user-portal.jar"]
    

  nginx-angular:
    restart: always
    build:
      context: .
      dockerfile: nginx.dockerfile
    expose:
      - "80"
    ports:
      - "8080:8080"
    depends_on:
      - user-portal-service
    networks:
      - user-app-network

networks:
  user-app-network:
    driver: bridge
